# Generated by Django 6.0.2 on 2026-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='entry',
            name='milk_type',
            field=models.CharField(max_length=10),
        ),
    ]
