# Generated by Django 6.0.2 on 2026-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_milksetting_remove_price_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MilkSetting',
        ),
        migrations.AlterField(
            model_name='entry',
            name='milk_type',
            field=models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=10),
        ),
    ]
